services:
  dashboard:
    build: .
    container_name: healthcare-sales-dashboard
    ports:
      - "8501:8501"
    volumes:
      # Mount .env for email agent API keys (optional)
      - ./.env:/app/.env:ro
      # Mount cache directory for email agent
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge